name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest
    env: 
      MINGW_PREFIX: "C:\\"
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Get cfltk
        shell: bash
        run: |
          git clone https://github.com/MoAlyousef/cfltk --depth=1 --recurse-submodules
          cd cfltk && ./scripts/bootstrap_common.sh
      - name: build
        shell: bash
        run: LDFLAGS="-LC:\\lib" CFLAGS="-IC:\\include" zig build --search-prefix "C:\\"
